repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
    -  id: pyupgrade
       args: ['--py38-plus']

  - repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
      - id: black
        args: ['--target-version', 'py38']
        exclude: 'doc/createDoc'

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        exclude: 'doc/createDoc'
